version: "3.7"

services:
  bundler:
    build:
      context: .
      dockerfile: Dockerfile
    command: node bundler.js
    working_dir: /app
    volumes:
      - ${PWD}/bundler.js:/app/bundler.js:ro
      - ${PWD}/SCRIPTS/BUNDLES:/app/BUNDLES:rw
      - ${PWD}/SCRIPTS/PROJECTS:/app/PROJECTS:ro
      - ${PWD}/SCRIPTS/GLOBALS:/app/GLOBALS:ro
      - ${PWD}/MODULES:/app/MODULES:ro
      - ${PWD}/.env:/app/.env:ro
